name: async_call_queue
description: AsyncCallQueue is a Dart class which provides a queuing mechanism to prevent concurrent access to asynchronous code.
version: 1.0.1
repository: https://github.com/ronjb/async_call_queue

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.5
